version: "3"


services:
  
  server:
   
    build: 
      context: ./server/
      dockerfile: Dockerfile
    
    volumes:
      - ./server:/server/

    network_mode: host

    command: python /server/server.py

    ports:
      - 5000:5000

  client:
   
    build: 
      context: ./client/
      dockerfile: Dockerfile

    volumes:
      - ./client:/client/

    command: python /client/client.py
    
    network_mode: host

    ports:
      - 5000:5000

    depends_on:
      - server