version: "3"

services:

  headnode:

    build: 
      context: ./headnode
      dockerfile: Dockerfile

    volumes:
      - ./headnode:/headnode/

    command: python headnode.py

    network_mode: host

    ports:
      - 5000-5007:5000-5007

    depends_on:
      - datanode1
      - datanode2
      - datanode3

  datanode1:

    build: 

      context: ./datanode1
      dockerfile: Dockerfile

    volumes:
      - ./datanode1:/datanode1/

    network_mode: host

    command: python /datanode1/datanode1.py

    ports:
      - 4000:4000

  datanode2:

    build: 
      context: ./datanode2
      dockerfile: Dockerfile

    volumes:
      - ./datanode2:/datanode2/

    network_mode: host

    command: python /datanode2/datanode2.py

    ports:
      - 4500:4500

  datanode3:

    build: 
      context: ./datanode3
      dockerfile: Dockerfile

    volumes:
      - ./datanode3:/datanode3/

    network_mode: host

    command: python /datanode3/datanode3.py

    ports:
      - 4700:4700

  client:

    build: 
      context: ./client
      dockerfile: Dockerfile

    volumes:
      - ./client:/client/

    network_mode: host

    command: python /client/client.py

    ports:
      - 5000:5000
      
    depends_on:
      - headnode